version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.25.0
jobs:
  job1:
    docker:
      - image: cimg/ruby:2.6.2
    steps:
      - run: echo dynamic configy
      - browser-tools/install-browser-tools:
          firefox-version: 63.0.3
          geckodriver-version: "v0.23.0"
      - browser-tools/install-chromedriver
workflows:
 workflow1:
  jobs:
   - job1
